name: linux

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.14'
          - 'latest'

    container:
      image: perl:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v3
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: cpanm --quiet --notest --installdeps .
      - name: Run Tests
        run: |
          perl Makefile.PL
          make test
